### PR TITLE
Added support for redirected requests

### PR DESCRIPTION
**Pull request by mcaskill**
Resolves #237 and provides a more flexible implementation.

The response header name to consult is configurable (`locationHeader`) and can be disabled with `false`; defaults to `X-SmoothState-Location`.

### CODE REVIEW

**Comment by quangmach** [comment]
@mcaskill Hi Chauncey, could you please explain how to use this? I'm trying to implement but the URL is not updated with the redirect one?

Thank you & Regards,
Quang Mach.

**Comment by mcaskill** [comment]
If you're using PHP and abiding to PSR-7 you would do something like this:

``` php
$redirection = 'some new destination';
$response->withHeader('X-SmoothState-Location', $redirection)->withRedirect($redirection, 302);
```

SmoothState takes care of updating the URI based on the value of the `locationHeader` option.

**Comment by derBoehm** [comment]
@mcaskill what do i wrong?

header('X-SmoothState-Location: /new_page');
header('Location: /new_page');
exit;

its still the old page after POST a form.

i try this one too

header('X-SmoothState-Location: /new_page');
include('new_page.php');
exit;

**Comment by mcaskill** [comment]
Hrm. Now that you mention it, I realize I haven't tried the `locationHeader` option with forms that redirect to a new URL.

Your first code snippet is the proper HTTP Header response to provide to SmoothState.

```
header('X-SmoothState-Location: /new_page');
header('Location: /new_page');
exit;
```

How are you submitting the form? Do you override the `submit` event and execute an AJAX request in that event's handler?

**Comment by Thumbleweed** [comment]
Hi!

I was looking in to this issue, because i also needed the feature. It took me a while to understand i had to add my own header to the response serverside :)

Anyway, it also works with forms.
added the header like this (laravel):

```php
public function thanks()
{
    return response()
        ->view('pages.quiz.thanks')
        ->header('x-smoothstate-location', action('QuizController@thanks'));
}
```

Works fine!

Thanks for the addition

**Pull request merged**
